### ISSUE TITLE
ClassNotFoundException when enabling plugin

### ISSUE THREAD

**Issue by toxicbyte** [KennethWussmann/Levitate-CLI#4]
I have made a plugin with who I have added 3 commands hadler classes that use Levitate. However I get a ClassNotFoundException on de.ketrwu.levitate.Levitate.

**Comment by KennethWussmann** [comment]
Hey,

are you developing a Bukkit / Spigot plugin? If yes please use [Levitate](https://github.com/KennethWussmann/Levitate).

Levitate-CLI is only for Java Command-Line-Interface Applications. 

Do you use Maven? - Do you use the JAR in your Build-Path?

Please be sure to pack your JAR-File with all dependencies. For Maven, take a look at [this post](http://stackoverflow.com/a/574650).

**Comment by toxicbyte** [comment]
Hey sorry I commented on the wrong project. Yes I used correct repository and dependencies with maven
On Mar 2, 2016 5:47 AM, Kenneth Wußmann <notifications@github.com> wrote:Hey,

are you developing a Bukkit / Spigot plugin? If yes please use Levitate.

Levitate-CLI is only for Java Command-Line-Interface Applications. 

Do you use Maven? - Do you use the JAR in your Build-Path?

Please be sure to pack your JAR-File with all dependencies. For Maven, take a look at this post.

**Comment by KennethWussmann** [comment]
Okay. I opened an issue in at Levitate for you.
Please use [this issue](https://github.com/KennethWussmann/Levitate/issues/11).
